Выполнить проект 8 спринта.
KotelnikovAV/java-kanban pull request #6
Opened 2024-04-04 17:00 UTC by KotelnikovAV

2024-04-05 19:04 UTC, desyatov-student requested changes
Пока основное описал.

2024-04-05 19:04 UTC, desyatov-student commented on src/service/InMemoryTaskManager.java
> +    public boolean addTakenInterval(Task task) {
проверка должна проходить по принципу взяли время и по ключу в мапе проверили есть значение или нет. Сейчас происходит цикл.

2024-04-05 19:04 UTC, desyatov-student commented on src/service/InMemoryTaskManager.java
> +    public boolean addTakenInterval(Task task) {
Интервалы по заданию 15 минут

2024-04-06 12:30 UTC, KotelnikovAV commented on src/service/FileBackedTaskManager.java
> +                task.setId(Integer.parseInt(splitTask[INDEX_ID]));
У меня тут такая логика: из файла считывается id задачи и соответственно присваивается задаче, находится максимальное id и передается в таскменеджер и в случае добавлении новых задач id будет рассчитываться из предположения, что все id до найденного максимального заняты.

2024-04-06 12:31 UTC, KotelnikovAV commented on src/service/FileBackedTaskManager.java
>          save();
Ну тут я свою логику уже объяснил в своем вопросе к твоему коду)

2024-04-06 12:32 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
> +        tasksByPriority = new TreeSet<>((task1, task2) -> {
Аналогично, уже объяснил в своем вопросе к твоему коду

2024-04-06 12:33 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
> +        Optional<Subtask> subtaskById = listSubtasks.stream().filter(subtask -> subtask.getId() == id).findFirst();
Да, я соглашусь, просто изначально не было требования по временной сложности поиска - вот я и сделал через список, а потом уже накладно было изменять)

2024-04-06 12:36 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
> +        if (!addTakenInterval(task)) {
Оно у меня сидит внутри метода addTakenInterval

2024-04-06 12:36 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
>      public void updateTask(int id, Task task) {
Согласен

2024-04-06 12:37 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
> +            removeTakenInterval(epicById.get());
У меня логика другая, что нужно проверить для тасок и епиков. Потому что если епик не перескается с чем-либо, то и сабтаска в нем автоматом ни с чем не пересекается

2024-04-06 12:37 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
> +        counterDone = epic.getSubtasks().stream().filter(subtask1 -> subtask1.getStatus().equals(Status.DONE)).count();
Согласен

2024-04-06 12:41 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
>      public void changeStatusEpic(Status status, Epic epic) {
Согласен, нужно учесть вариант с IN_PROGRESS

2024-04-06 12:41 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
> +    public boolean addTakenInterval(Task task) {
Просто решил сделать чуть лучше

2024-04-06 12:43 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
> +    public boolean addTakenInterval(Task task) {
Ну в ТЗ было условие сделать за O(1), у меня это и проиходит. Поиск пересечений не зависит от количества тасок. Но вот просто это тот алгоритм, который мне пришел в голову на момент написания

2024-04-06 12:43 UTC, KotelnikovAV commented on src/model/Epic.java
> +    public LocalDateTime getEndTime() {
Да, наверное лучше будет так, согласен

2024-04-06 12:44 UTC, KotelnikovAV commented on src/model/Epic.java
> +    public void setStartTime(String startTime) {
Подумал, что выгдядит вполне читаемо, поэтому не разделил

2024-04-06 12:44 UTC, KotelnikovAV commented on src/model/Subtask.java
> +    public Subtask(Epic epic, String task, String startTime, String durationTask) {
Да, соглашусь

2024-04-06 17:03 UTC, desyatov-student commented on src/service/FileBackedTaskManager.java
> +                task.setId(Integer.parseInt(splitTask[INDEX_ID]));
Идея интересная. ты прав. Только в этой строчке когда это никак не влияет. ты же описание, имя передаешь в конструктор значит и id можно передать

2024-04-06 17:06 UTC, desyatov-student commented on src/service/InMemoryTaskManager.java
> +        if (!addTakenInterval(task)) {
Как пользователь узнаешь что таска не создалась ?

2024-04-06 17:08 UTC, desyatov-student commented on src/service/InMemoryTaskManager.java
> +            removeTakenInterval(epicById.get());
В задании четка говорится про таски и сабтаски. Пример: между сабтасками может быть "окно". например несколько часов. Туда можно воткнуть еще таску

2024-04-06 17:17 UTC, desyatov-student commented on src/service/FileBackedTaskManager.java
> +        takenInterval.clear();
А занятые интервалы будут где то заполняться полученные из файла ?

2024-04-06 19:36 UTC, KotelnikovAV commented on src/service/InMemoryTaskManager.java
> +            removeTakenInterval(epicById.get());
Убедил

2024-04-06 19:37 UTC, KotelnikovAV commented on src/service/FileBackedTaskManager.java
> +        takenInterval.clear();
Да, таска достается из файла и идет стандартная процедура добавления задачи в таскменеджер

2024-04-13 15:12 UTC, closed without merging